testname: webMUSHRA Example
testId: headphones_screen_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to webMUSHRA!       
    - type: volume
      id: vol
      name: Volume settings
      content: Bitte benutzen Sie Kopfhörer und stellen die Lautstärke auf einen angenehmen Wert ein!
      stimulus: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_calibration.wav
      defaultVolume: 0.5
    - type: headphones_screen
      id: hp_check
      name: Headphones check
      repetitions: 6
      target: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_1.wav
      other: 
        A: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_2.wav
        B: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_3.wav
    - type: preference_test
      id: trialpref
      name: Preference test
      content: |
        <p><b>Which sound do you prefer?</b></p>
      considerOrder: true
      stimuli:
          - A1: configs/resources/audio/1.wav
            A2: configs/resources/audio/2.wav
            A3: configs/resources/audio/3.wav
            A4: configs/resources/audio/4.wav
            A5: configs/resources/audio/5.wav
          - B1: configs/resources/audio/6.wav
            B2: configs/resources/audio/7.wav
            B3: configs/resources/audio/8.wav
            B4: configs/resources/audio/9.wav
            B5: configs/resources/audio/10.wav
          - C1: configs/resources/audio/11.wav
            C2: configs/resources/audio/12.wav
            C3: configs/resources/audio/13.wav
            C4: configs/resources/audio/14.wav
            C5: configs/resources/audio/15.wav
          - D1: configs/resources/audio/16.wav
            D2: configs/resources/audio/17.wav
            D3: configs/resources/audio/18.wav
            D4: configs/resources/audio/19.wav
            D5: configs/resources/audio/20.wav
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      generateSubjectId: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
