testname: webMUSHRA Example
testId: headphones_screen_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to webMUSHRA!
    - type: consent
      id: consent_page
      name: Datenschutz- und Einwilligungserklärung für das Forschungsprojekt oder Experiment <strong>Prosodievorhersage</strong>
      mustConsent: true
      content: <h1> Versuchsleiter: Simon Sieben</h1>
      <h1> Zweck und datenerhebende Stelle </h1>
      <p>You are participating in a listening test. For this, we want to store the answers you give to the following questions.<br>Do you give consent for this?</p>       
    - type: volume
      id: vol
      name: Volume settings
      content: Bitte benutzen Sie Kopfhörer und stellen die Lautstärke auf einen angenehmen Wert ein!
      stimulus: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_calibration.wav
      defaultVolume: 0.5
    - type: headphones_screen
      id: hp_check
      name: Headphones check
      repetitions: 3
      target: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_1.wav
      other: 
        A: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_2.wav
        B: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_3.wav
    - type: preference_test
      id: trialpref
      name: Preference test
      content: |
        <p><b>Welcher Klang wirkt natürlicher?</b></p>
      considerOrder: true
      stimuli:
          - A1: configs/resources/audio/1.wav
            A2: configs/resources/audio/2.wav
            A3: configs/resources/audio/3.wav
            A4: configs/resources/audio/4.wav
            A5: configs/resources/audio/5.wav
    - type: finish
      name: Thank you
      content: Vielen Dank für die Teilnahme!
      showResults: true
      writeResults: true
      generateSubjectId: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
