testname: webMUSHRA Example
testId: prosody_experiment
bufferSize: 8192
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Willkommen zum Hörexperiment!
      content: Willkommen zum Hörexperiment zur Prosodievorhersage! Da im Folgenden sehr kleine Klangunterschiede bewertet werden sollen bitten wir Sie Kopfhörer zu benutzen. Nach der Einwilligungserklärung erfolgt gleich zunächst ein kurzer Kopfhörertest, in dem sie 6 mal denjenigen von drei Klängen identifizieren, welcher über Kopfhörer scheinbar einen tiefen Piepton enthält. Anschließend folgt das eigentliche Hörexperiment, welches ca. 60-90 Minuten in Anspruch nimmt. In diesem soll von jeweils zwei synthetisierten Sprachäußerungen diejenige ausgewählt werden, welche in Bezug auf Sprachrhythmus und Sprachmelodie natürlicher wirkt. Dafür muss jede synthetisierte Äußerung zumindest einmal komplett abgespielt werden, ein wiederholtes Hören ist aber auch möglich und bei Unsicherheit erwünscht. Für jedes Paar muss eine Präferenz abgegeben werden. Das Experiment endet schließlich mit einer demographischen Erhebung.
    - type: consent
      id: consent_page
      name: Datenschutz- und Einwilligungserklärung für das Forschungsprojekt oder Experiment <strong>Prosodievorhersage</strong>
      mustConsent: true
      content: <div align="left"><h3>Versuchsleiter: Simon Sieben</h3><p align="left"><strong>Versuchsleiter: Simon Sieben</strong><br><br><strong>Zweck und datenerhebende Stelle</strong><br>Im Rahmen der Studie „Prosodievorhersage“ wird die Bewertung der Natürlichkeit der Betonung synthetisierter Sprache durch die potenziellen Nutzer durch Perzeptionstests untersucht. Die Testperson bekommt eine Reihe von synthetisierten Satzpaaren mit verschiedenen Synthese-Varianten mit unterschiedlich generierten Satz-Betonungen dargeboten. Es soll jeweils der natürlicher klingende Satz ausgewählt werden. Alleinig für vorgenannten Forschungszweck sollen personenbezogene Daten durch die TU Dresden, Fakultät Elektrotechnik und Informationstechnik, Professur für Sprachtechnologie und Kognitive Systeme, 01062 Dresden, E-Mail kogsys@mailbox.tu-dresden.de verarbeitet werden (Verarbeitung im Sinne von Erhebung, Speicherung, Veränderung und Nutzung). Hierzu ist eine freiwillige und informierte Einwilligung erforderlich. </p></div>
    - type: volume
      id: vol
      name: Lautstärkeeinstellung
      content: Bitte benutzen Sie Kopfhörer und stellen die Lautstärke auf einen angenehmen Wert ein!
      stimulus: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_calibration.wav
      defaultVolume: 0.5
    - type: headphones_screen
      id: hp_check
      name: Headphones check
      repetitions: 6
      target: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_1.wav
      other: 
        A: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_2.wav
        B: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_3.wav
    - type: preference_test
      id: trialpref
      name: Preference test
      content: |
        <p><b>Welcher Klang wirkt natürlicher?</b></p>
      considerOrder: true
      stimuli:
          - A1: configs/resources/audio/listening_experiment/extra_pos_2.wav
            A2: configs/resources/audio/listening_experiment/extra_probability_2.wav
            A3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_2.wav
            A4: configs/resources/audio/listening_experiment/extra_word_freq_2.wav
            A5: configs/resources/audio/listening_experiment/vergleich_2.wav
          - B1: configs/resources/audio/listening_experiment/extra_pos_4.wav
            B2: configs/resources/audio/listening_experiment/extra_probability_4.wav
            B3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_4.wav
            B4: configs/resources/audio/listening_experiment/extra_word_freq_4.wav
            B5: configs/resources/audio/listening_experiment/vergleich_4.wav
          - C1: configs/resources/audio/listening_experiment/extra_pos_5.wav
            C2: configs/resources/audio/listening_experiment/extra_probability_5.wav
            C3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_5.wav
            C4: configs/resources/audio/listening_experiment/extra_word_freq_5.wav
            C5: configs/resources/audio/listening_experiment/vergleich_5.wav
    - type: finish
      name: Thank you
      content: Vielen Dank für die Teilnahme!
      showResults: true
      writeResults: true
      generateSubjectId: true
      questionnaire:
          - type: text
            label: eMail (falls Angabe unerwünscht einfach x in das Feld eintragen)
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Frau
             - value: male
               label: Mann
             - value: other
               label: Divers
