testname: Hörexperiment Prosodievorhersage
testId: prosody_experiment_29
bufferSize: 4096
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Willkommen zum Hörexperiment!
      content: |
        <p> Willkommen zum Hörexperiment zur Prosodievorhersage!</p> 
        <p> Da im Folgenden sehr kleine Klangunterschiede bewertet werden sollen, bitten wir Sie Kopfhörer zu benutzen. </p>
        <p> Nach der Einwilligungserklärung erfolgt gleich zunächst ein kurzer Kopfhörertest, in dem sie 6 mal denjenigen von drei Klängen identifizieren, welcher über Kopfhörer scheinbar einen tiefen Piepton enthält. </p> 
        <p>Anschließend folgt das eigentliche Hörexperiment, welches ca. 30-40 Minuten in Anspruch nimmt. In diesem soll von jeweils zwei synthetisierten Sprachäußerungen diejenige ausgewählt werden, welche in Bezug auf Sprachrhythmus und Sprachmelodie natürlicher wirkt. Dafür muss jede synthetisierte Äußerung zumindest einmal komplett abgespielt werden, ein wiederholtes Hören ist aber auch möglich und bei Unsicherheit erwünscht. Für jedes Paar muss eine Präferenz abgegeben werden.</p>
        <p> Das Experiment endet schließlich mit einer kurzen demographischen Erhebung.</p>
    - type: consent
      id: consent_page
      name: Datenschutz- und Einwilligungserklärung für das Forschungsprojekt oder Experiment <strong>Prosodievorhersage</strong>
      mustConsent: true
      content: | 
        <div align="left">
        <h3>Versuchsleiter: Simon Sieben</h3>
        <h3>Zweck und datenerhebende Stelle</h3>
        <p>Im Rahmen der Studie „Prosodievorhersage“ wird die Bewertung der Natürlichkeit der Betonung synthetisierter Sprache durch die potenziellen Nutzer durch Perzeptionstests untersucht.</p>
        <p>Die Testperson bekommt eine Reihe von synthetisierten Satzpaaren mit verschiedenen Synthese-Varianten mit unterschiedlich generierten Satz-Betonungen dargeboten. Es soll jeweils der natürlicher klingende Satz ausgewählt werden. </p>
        <p>Alleinig für vorgenannten Forschungszweck sollen personenbezogene Daten durch die TU Dresden, Fakultät Elektrotechnik und Informationstechnik, Professur für Sprachtechnologie und Kognitive Systeme, 01062 Dresden, E-Mail kogsys@mailbox.tu-dresden.de verarbeitet werden (Verarbeitung im Sinne von Erhebung, Speicherung, Veränderung und Nutzung). </p> 
        <p>Hierzu ist eine freiwillige und informierte Einwilligung erforderlich. </p> 

        <h3>Datenverarbeitung</h3>
        <p> Die personenbezogenen Daten für jede Testperson (probandenbezogene Metadaten (Vorname, Familienname, Wohnort, Alter, Geschlecht, Muttersprache, Vergütung) werden den gesetzlichen Vorschriften entsprechend geschützt. </p>
        <p> Die probandenbezogenen Daten werden getrennt von den Testdaten aufgezeichnet und vor der Verarbeitung der inhaltlichen Daten pseudonymisiert. Diesem Zweck dient eine Codeliste, die jedem Probandennamen eine alphanumerische Codierung (Probanden-ID) zuordnet. Die Codeliste wird nicht elektronisch gespeichert, sondern ausgedruckt und im Sekretariat der Professur unter Verschluss aufbewahrt. </p>
        <p> Inhaltliche Daten (z.B. Antworten bzw. Auswahlentscheidungen während der Perzeptionstests, Reaktionszeiten/ Reaktionsmuster etc.) werden zwecks softwaregestützter Auswertung elektronisch gespeichert. </p>
        <p> Sofern demografische Angaben für die Auswertung der Tests von Bedeutung sind, werden pseudonymisierte Probandenprofile angelegt, die anstelle der Namen die Probanden-IDs enthalten. </p>
        <p> Wir sichern Ihnen zu, dass die Daten unverzüglich anonymisiert werden, sobald es der Forschungszweck erlaubt. Es kann jedoch unter Umständen und im Einzelfall möglich sein, dass keine vollständige Anonymisierung möglich ist. </p>

        <h3>Freiwilligkeit und Widerruf</h3>
        <p> Die Teilnahme an den Perzeptionstest sowie die Mitteilung personenbezogener Angaben im Zusammenhang mit der Teilnahme an den Perzeptionstests sind freiwillig. Die Teilnahme an den Tests sowie die Erhebung, Speicherung und Nutzung der Daten bedürfen der schriftlichen Einwilligung. Sie können Ihre Einwilligung jederzeit ohne Angabe von Gründen mit Wirkung auf die Zukunft widerrufen. </p>
        <p> Im Fall der Verweigerung oder des Widerrufs der Einwilligung entstehen Ihnen keine Nachteile. </p>
        <p> Wir weisen Sie darauf hin, dass Sie bis zum Zeitpunkt der Veröffentlichung die Löschung Ihrer Daten verlangen können, sofern diese individuell zuordenbar sind. </p>

        <h3>Datenübermittlungs</h3>
        <p>Insofern dies nicht anders gesetzlich bestimmt ist oder Sie im Einzelfall ausdrücklich eingewilligt haben, erfolgt keine Übermittlung von personenbezogenen Daten an Dritte.</p>

        <h3>Speicherdauer</h3>
        <p>Die im Zusammenhang mit dem Forschungsprojekt erhobenen inhaltlichen Daten werden 10 Jahre gespeichert. Alle personenbezogenen Daten werden nach Abschluss des Forschungsprojektes datenschutzgerecht gelöscht.</p>

        <h3>Veröffentlichung</h3>
        <p>Die Ergebnisse der Studie werden in wissenschaftlichen Publikationen veröffentlicht. In Veröffentlichungen werden die auf Versuchspersonen bezogenen Daten stets anonymisiert.</p>

        <h3>Auskunftsrecht</h3>
        <p>Mir ist bekannt, dass ich jederzeit Auskunft über die zu meiner Person verarbeiteten Daten sowie die möglichen Empfänger dieser Daten, an die diese übermittelt wurden, verlangen kann und mir eine Antwort mit der Frist von einem Monat nach Eingang des Auskunftsersuchens zusteht.</p>

        <h3>Datenschutzbeauftragter und Aufsichtsbehörde für den Datenschutz</h3>
        <p>Mir ist bekannt, dass ich mich jederzeit an den Datenschutzbeauftragten der TU Dresden (https://tu-dresden.de/impressum#ck_datenschutz) sowie an die zuständige Aufsichtsbehörde (https://www.saechsdsb.de/impressum-datenschutzerklaerung) für den Datenschutz wenden kann.</p>
        </div>
    - type: volume
      id: vol
      name: Lautstärkeeinstellung
      content: Bitte benutzen Sie Kopfhörer und stellen die Lautstärke auf einen angenehmen Wert ein!
      stimulus: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_calibration.wav
      defaultVolume: 0.5
    - type: headphones_screen
      id: hp_check
      name: Kopfhörertest
      repetitions: 6
      target: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_1.wav
      other: 
        A: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_2.wav
        B: configs/resources/audio/stimuli_HugginsPitch/HugginsPitch_3.wav
    - type: preference_test
      id: trialpref
      name: Hörexperiment
      content: |
        <p><b>Welche Äußerung klingt natürlicher in Bezug auf Sprachrhythmus und -melodie?</b></p>
      considerOrder: true
      stimuli:
          - A1: configs/resources/audio/listening_experiment/extra_pos_2.wav
            A2: configs/resources/audio/listening_experiment/extra_probability_2.wav
            A3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_2.wav
            A4: configs/resources/audio/listening_experiment/extra_word_freq_2.wav
            A5: configs/resources/audio/listening_experiment/vergleich_2.wav
          - B1: configs/resources/audio/listening_experiment/extra_pos_4.wav
            B2: configs/resources/audio/listening_experiment/extra_probability_4.wav
            B3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_4.wav
            B4: configs/resources/audio/listening_experiment/extra_word_freq_4.wav
            B5: configs/resources/audio/listening_experiment/vergleich_4.wav
          - C1: configs/resources/audio/listening_experiment/extra_pos_5.wav
            C2: configs/resources/audio/listening_experiment/extra_probability_5.wav
            C3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_5.wav
            C4: configs/resources/audio/listening_experiment/extra_word_freq_5.wav
            C5: configs/resources/audio/listening_experiment/vergleich_5.wav
          - D1: configs/resources/audio/listening_experiment/extra_pos_6.wav
            D2: configs/resources/audio/listening_experiment/extra_probability_6.wav
            D3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_6.wav
            D4: configs/resources/audio/listening_experiment/extra_word_freq_6.wav
            D5: configs/resources/audio/listening_experiment/vergleich_6.wav
          - E1: configs/resources/audio/listening_experiment/extra_pos_7.wav
            E2: configs/resources/audio/listening_experiment/extra_probability_7.wav
            E3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_7.wav
            E4: configs/resources/audio/listening_experiment/extra_word_freq_7.wav
            E5: configs/resources/audio/listening_experiment/vergleich_7.wav
          - F1: configs/resources/audio/listening_experiment/extra_pos_11.wav
            F2: configs/resources/audio/listening_experiment/extra_probability_11.wav
            F3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_11.wav
            F4: configs/resources/audio/listening_experiment/extra_word_freq_11.wav
            F5: configs/resources/audio/listening_experiment/vergleich_11.wav
          - G1: configs/resources/audio/listening_experiment/extra_pos_12.wav
            G2: configs/resources/audio/listening_experiment/extra_probability_12.wav
            G3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_12.wav
            G4: configs/resources/audio/listening_experiment/extra_word_freq_12.wav
            G5: configs/resources/audio/listening_experiment/vergleich_12.wav
          - H1: configs/resources/audio/listening_experiment/extra_pos_14.wav
            H2: configs/resources/audio/listening_experiment/extra_probability_14.wav
            H3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_14.wav
            H4: configs/resources/audio/listening_experiment/extra_word_freq_14.wav
            H5: configs/resources/audio/listening_experiment/vergleich_14.wav
          - I1: configs/resources/audio/listening_experiment/extra_pos_17.wav
            I2: configs/resources/audio/listening_experiment/extra_probability_17.wav
            I3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_17.wav
            I4: configs/resources/audio/listening_experiment/extra_word_freq_17.wav
            I5: configs/resources/audio/listening_experiment/vergleich_17.wav
          - J1: configs/resources/audio/listening_experiment/extra_pos_19.wav
            J2: configs/resources/audio/listening_experiment/extra_probability_19.wav
            J3: configs/resources/audio/listening_experiment/extra_probability_pos_tag_word_freq_19.wav
            J4: configs/resources/audio/listening_experiment/extra_word_freq_19.wav
            J5: configs/resources/audio/listening_experiment/vergleich_19.wav
    - type: finish
      name: Vielen Dank!
      content: Vielen Dank für die Teilnahme!
      showResults: false
      writeResults: true
      generateSubjectId: true
      confirmationCode: WMY2SAXX
      questionnaire:
          - type: text
            label: E-Mail (falls Angabe unerwünscht einfach x in das Feld eintragen)
            name: email
          - type: number
            label: Alter
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: weiblich
             - value: male
               label: männlich
             - value: other
               label: divers
